### ISSUE TITLE
JSONException

### ISSUE THREAD

**Issue by Kaito23** [migtavares/owmClient#8]
Hey, 

I just tried the example and I get a JSONException:

```
org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
	at org.json.JSONObject.<init>(JSONObject.java:179)
	at org.json.JSONObject.<init>(JSONObject.java:402)
	at org.bitpipeline.lib.owm.OwmClient.doQuery(OwmClient.java:295)
	at org.bitpipeline.lib.owm.OwmClient.currentWeatherAtCity(OwmClient.java:197)
	at Main.test(Main.java:21)
	at Main.main(Main.java:13)
```

```

import java.io.IOException;

import org.bitpipeline.lib.owm.OwmClient;
import org.bitpipeline.lib.owm.WeatherData;
import org.bitpipeline.lib.owm.WeatherData.WeatherCondition;
import org.bitpipeline.lib.owm.WeatherStatusResponse;
import org.json.JSONException;

public class Main {

	public static void main(final String[] args) {
		try {
			test();
		} catch (IOException | JSONException e) {
			e.printStackTrace();
		}
	}

	private static void test() throws IOException, JSONException {
		final OwmClient owm = new OwmClient();
		final WeatherStatusResponse currentWeather = owm.currentWeatherAtCity("Tokyo", "JP");
		if (currentWeather.hasWeatherStatus()) {
			final WeatherData weather = currentWeather.getWeatherStatus().get(0);
			if (weather.getPrecipitation() == Integer.MIN_VALUE) {
				final WeatherCondition weatherCondition = weather.getWeatherConditions().get(0);
				final String description = weatherCondition.getDescription();
				if (description.contains("rain") || description.contains("shower"))
					System.out.println("No rain measures in Tokyo but reports of " + description);
				else
					System.out.println("No rain measures in Tokyo: " + description);
			} else
				System.out.println("It's raining in Tokyo: " + weather.getPrecipitation() + " mm/h");
		}
	}

}

```

So is this problem known?

Edit: 
I debuged everything and I see the response is 502 (Bad Gateway) in OwmClient 261.

Greetings
Kaito

**Comment by migtavares** [comment]
Yes, it's known.
OWM now requires a API key to be used.
Also, the API 2.1 is disabled. I didn't manage to find the time to implement and test the 2.5 API. Sorry for that.
I cannot provide a ETA for the release that supports OWM 2.5 API but I am trying to finish up the implementation and some improvements.

**Comment by akeshwarj** [comment]
@migtavares Is the API 2.5 available now?
